### ISSUE TITLE
Refactoring for BTTB

### ISSUE THREAD

**Issue by jha92** [beam-telescopes/eutelescope#9]
Hi,

I am currently doing some refactoring of the processors (https://github.com/beam-telescopes/eutelescope/tree/gbl_work_refactor), we need for GBL.
In the course of this, I would find it useful, to discuss some topics directly. My idea would be a small hackathon on a day.
This would allow us to have EUTel in a good shape for BTTB as well as for the paper release.

What do you think?

**Comment by dreyling** [comment]
Yes!!! :) When do you, @jha92  have time tomorrow?

We should merge it, and then focus on the tutorials.

**Comment by TCThenna** [comment]
when do you want to meet? Today, 13 - 15?

**Comment by jha92** [comment]
Yes, we said after lunch, so around 1PM should be right. Topics are:
- some open code questions
- merge diverse gbl_work branches into one
- discuss merging/tagging with official repo
- installation guide for BTTB
- AOB

**Comment by edorossi** [comment]
Can we do it at 2 instead?

**Comment by TCThenna** [comment]
I have to leave at 15
